name: Go testing

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.3.0
        with:
          submodules: "true"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
        id: go

      - name: Get dependencies
        run: |
          make install

      - name: Test
        run: make test
